services:
  llm-provider:
    image: nycusdc/sciedu-llm:dev
    container_name: sciedu-llm-provider-dev
    networks:
      - traefik
    environment:
      HOST: 0.0.0.0
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: "https://portal.genai.nchc.org.tw/api"
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
      LANGFUSE_BASE_URL: "https://langfuse-sciedu.sdc.nycu.club"

    labels:
      - "vector.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.sciedu-llm-dev.rule=Host(`llm.dev.sciedu.sdc.nycu.club`)"
      - "traefik.http.routers.sciedu-llm-dev.entrypoints=websecure"
      - "traefik.http.routers.sciedu-llm-dev.tls=true"
      - "traefik.http.routers.sciedu-llm-dev.tls.certresolver=cloudflare"
      - "traefik.http.services.sciedu-llm-dev.loadbalancer.server.port=8080"

  llm-judge-ui:
    image: nycusdc/sciedu-llm:dev
    container_name: sciedu-llm-judge-ui-dev
    command: ["python", "-m", "eval_ui.main"]
    networks:
      - traefik
    environment:
      HOST: 0.0.0.0
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: "https://portal.genai.nchc.org.tw/api"
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
      LANGFUSE_BASE_URL: "https://langfuse-sciedu.sdc.nycu.club"

    labels:
      - "vector.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.sciedu-llm-judge-ui-dev.rule=Host(`sciedu-judge-ci.sdc.nycu.club`)"
      - "traefik.http.routers.sciedu-llm-judge-ui-dev.entrypoints=websecure"
      - "traefik.http.routers.sciedu-llm-judge-ui-dev.tls=true"
      - "traefik.http.routers.sciedu-llm-judge-ui-dev.tls.certresolver=cloudflare"
      - "traefik.http.services.sciedu-llm-judge-ui-dev.loadbalancer.server.port=7860"

networks:
  traefik:
    external: true
