services:
  llm-provider:
    image: nycusdc/sciedu-llm:stage
    container_name: sciedu-llm-provider-stage
    networks:
      - traefik
    environment:
      HOST: 0.0.0.0
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: "https://portal.genai.nchc.org.tw/api"
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
      LANGFUSE_BASE_URL: "https://langfuse-sciedu.sdc.nycu.club"

    labels:
      - "vector.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.sciedu-llm-stage.rule=Host(`llm.stage.sciedu.sdc.nycu.club`)"
      - "traefik.http.routers.sciedu-llm-stage.entrypoints=websecure"
      - "traefik.http.routers.sciedu-llm-stage.tls=true"
      - "traefik.http.routers.sciedu-llm-stage.tls.certresolver=cloudflare"
      - "traefik.http.services.sciedu-llm-stage.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true
